### ISSUE TITLE
java.net.SocketException: Bind failed with error no: 24

### ISSUE THREAD

**Issue by HhjWxx** [sunchaoqun/spring-boot-nitro-enclaves#1]
After running for a period of time, this exception must occur. How can I solve it

**Comment by HhjWxx** [comment]
java.net.SocketException: Bind failed with error no: 24
        at solutions.cloudarchitects.vsockj.VSockImpl.accept(Native Method) ~[vsockj-core-1.0-SNAPSHOT.jar!/:na]
        at solutions.cloudarchitects.vsockj.ServerVSock.accept(ServerVSock.java:15) ~[vsockj-core-1.0-SNAPSHOT.jar!/:na]
        at com.myx.enclaves.enclave.server.network.vsock.SockListener.accept(SockListener.java:49) ~[myx-enclave-boot-starter-1.0-SNAPSHOT.jar!/:1.0-SNAPSHOT]
        at com.myx.enclaves.enclave.server.NitroEnclaveServer.run(NitroEnclaveServer.java:48) ~[myx-enclave-boot-starter-1.0-SNAPSHOT.jar!/:1.0-SNAPSHOT]
        at com.myx.enclave.NitroEnclaveApplication.main(NitroEnclaveApplication.java:23) [classes!/:1.0-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_382]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_382]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_382]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_382]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [app.jar:1.0-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [app.jar:1.0-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [app.jar:1.0-SNAPSHOT]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [app.jar:1.0-SNAPSHOT]

**Comment by qings2329** [comment]
run the following command:

ulimit -n 655360

**Comment by qings2329** [comment]
VSockImpl has a bug, it can't close all sockets which are created when  it hands request  each time . This causes resource leak by opening too much file descriptor .

**Comment by sunchaoqun** [comment]
checking

**Comment by HhjWxx** [comment]
I have resigned from my previous company. Thank you very much for your feedback

**Comment by sunchaoqun** [comment]
[vsockj-core.zip](https://github.com/user-attachments/files/17295648/vsockj-core.zip)
Please replace the jar file and also about the so file will print more infos. 
you can check the github which I committed
https://github.com/sunchaoqun/vsockj
